# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistical_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticalAnalysis(object):
    def setupUi(self, StatisticalAnalysis):
        StatisticalAnalysis.setObjectName("StatisticalAnalysis")
        StatisticalAnalysis.resize(1040, 948)
        self.label = QtWidgets.QLabel(StatisticalAnalysis)
        self.label.setGeometry(QtCore.QRect(40, 20, 131, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"font: 20pt \"宋体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(StatisticalAnalysis)
        self.label_2.setGeometry(QtCore.QRect(420, 40, 31, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(StatisticalAnalysis)
        self.pushButton.setGeometry(QtCore.QRect(780, 60, 201, 61))
        self.pushButton.setStyleSheet("\n"
"font: 16pt \"宋体\";")
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(StatisticalAnalysis)
        self.tableView.setGeometry(QtCore.QRect(40, 240, 941, 631))
        self.tableView.setObjectName("tableView")
        self.label_3 = QtWidgets.QLabel(StatisticalAnalysis)
        self.label_3.setGeometry(QtCore.QRect(170, 190, 121, 61))
        self.label_3.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(StatisticalAnalysis)
        self.label_4.setGeometry(QtCore.QRect(740, 180, 121, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_4.setObjectName("label_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(StatisticalAnalysis)
        self.dateTimeEdit.setGeometry(QtCore.QRect(160, 30, 241, 41))
        self.dateTimeEdit.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.dateTimeEdit.setDisplayFormat("yyyy-M-d H:mm:ss")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(StatisticalAnalysis)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(470, 30, 251, 41))
        self.dateTimeEdit_3.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.dateTimeEdit_3.setDisplayFormat("yyyy-M-d H:mm:ss")
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.label_5 = QtWidgets.QLabel(StatisticalAnalysis)
        self.label_5.setGeometry(QtCore.QRect(40, 110, 141, 51))
        self.label_5.setStyleSheet("\n"
"font: 20pt \"宋体\";")
        self.label_5.setObjectName("label_5")
        self.time_le = QtWidgets.QLineEdit(StatisticalAnalysis)
        self.time_le.setGeometry(QtCore.QRect(190, 110, 211, 41))
        self.time_le.setStyleSheet("\n"
"font: 15pt \"宋体\";")
        self.time_le.setObjectName("time_le")

        self.retranslateUi(StatisticalAnalysis)
        QtCore.QMetaObject.connectSlotsByName(StatisticalAnalysis)

    def retranslateUi(self, StatisticalAnalysis):
        _translate = QtCore.QCoreApplication.translate
        StatisticalAnalysis.setWindowTitle(_translate("StatisticalAnalysis", "Dialog"))
        self.label.setText(_translate("StatisticalAnalysis", "时间段"))
        self.label_2.setText(_translate("StatisticalAnalysis", "——"))
        self.pushButton.setText(_translate("StatisticalAnalysis", "点我开始统计"))
        self.label_3.setText(_translate("StatisticalAnalysis", "车流统计"))
        self.label_4.setText(_translate("StatisticalAnalysis", "绿灯统计"))
        self.label_5.setText(_translate("StatisticalAnalysis", "时间间隔"))
