# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startcollect_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startCollect_dialog(object):
    def setupUi(self, startCollect_dialog):
        startCollect_dialog.setObjectName("startCollect_dialog")
        startCollect_dialog.resize(1277, 857)
        self.label = QtWidgets.QLabel(startCollect_dialog)
        self.label.setGeometry(QtCore.QRect(510, 20, 161, 51))
        self.label.setStyleSheet("\n"
"font: 20pt \"宋体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(startCollect_dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 111, 31))
        self.label_2.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(startCollect_dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 160, 111, 21))
        self.label_3.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_3.setObjectName("label_3")
        self.startcollect_btn = QtWidgets.QPushButton(startCollect_dialog)
        self.startcollect_btn.setGeometry(QtCore.QRect(830, 100, 161, 41))
        self.startcollect_btn.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.startcollect_btn.setObjectName("startcollect_btn")
        self.label_4 = QtWidgets.QLabel(startCollect_dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 270, 111, 31))
        self.label_4.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(startCollect_dialog)
        self.label_5.setGeometry(QtCore.QRect(170, 320, 101, 31))
        self.label_5.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(startCollect_dialog)
        self.label_6.setGeometry(QtCore.QRect(170, 370, 101, 31))
        self.label_6.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(startCollect_dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 280, 81, 31))
        self.label_7.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(startCollect_dialog)
        self.label_8.setGeometry(QtCore.QRect(860, 280, 141, 31))
        self.label_8.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(startCollect_dialog)
        self.label_9.setGeometry(QtCore.QRect(440, 280, 101, 31))
        self.label_9.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(startCollect_dialog)
        self.label_10.setGeometry(QtCore.QRect(710, 280, 91, 31))
        self.label_10.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_10.setObjectName("label_10")
        self.ew_vehichecount_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.ew_vehichecount_le.setGeometry(QtCore.QRect(280, 320, 71, 31))
        self.ew_vehichecount_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.ew_vehichecount_le.setObjectName("ew_vehichecount_le")
        self.sn_vehichecount_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.sn_vehichecount_le.setGeometry(QtCore.QRect(280, 370, 71, 31))
        self.sn_vehichecount_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.sn_vehichecount_le.setObjectName("sn_vehichecount_le")
        self.ew_process_text = QtWidgets.QTextBrowser(startCollect_dialog)
        self.ew_process_text.setGeometry(QtCore.QRect(30, 510, 601, 331))
        self.ew_process_text.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.ew_process_text.setObjectName("ew_process_text")
        self.sn_process_text = QtWidgets.QTextBrowser(startCollect_dialog)
        self.sn_process_text.setGeometry(QtCore.QRect(680, 511, 581, 331))
        self.sn_process_text.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.sn_process_text.setObjectName("sn_process_text")
        self.label_13 = QtWidgets.QLabel(startCollect_dialog)
        self.label_13.setGeometry(QtCore.QRect(240, 470, 231, 21))
        self.label_13.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(startCollect_dialog)
        self.label_14.setGeometry(QtCore.QRect(850, 470, 231, 21))
        self.label_14.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_14.setObjectName("label_14")
        self.ew_vehiche_begintime_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.ew_vehiche_begintime_le.setGeometry(QtCore.QRect(370, 320, 221, 31))
        self.ew_vehiche_begintime_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.ew_vehiche_begintime_le.setObjectName("ew_vehiche_begintime_le")
        self.sn_vehiche_begintime_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.sn_vehiche_begintime_le.setGeometry(QtCore.QRect(370, 370, 221, 31))
        self.sn_vehiche_begintime_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.sn_vehiche_begintime_le.setObjectName("sn_vehiche_begintime_le")
        self.ew_vehiche_endtime_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.ew_vehiche_endtime_le.setGeometry(QtCore.QRect(650, 320, 201, 31))
        self.ew_vehiche_endtime_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.ew_vehiche_endtime_le.setObjectName("ew_vehiche_endtime_le")
        self.sn_vehiche_endtime_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.sn_vehiche_endtime_le.setGeometry(QtCore.QRect(650, 370, 201, 31))
        self.sn_vehiche_endtime_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.sn_vehiche_endtime_le.setObjectName("sn_vehiche_endtime_le")
        self.ew_light_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.ew_light_le.setGeometry(QtCore.QRect(890, 320, 71, 31))
        self.ew_light_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.ew_light_le.setObjectName("ew_light_le")
        self.sn_light_le = QtWidgets.QLineEdit(startCollect_dialog)
        self.sn_light_le.setGeometry(QtCore.QRect(890, 370, 71, 31))
        self.sn_light_le.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.sn_light_le.setObjectName("sn_light_le")
        self.line = QtWidgets.QFrame(startCollect_dialog)
        self.line.setGeometry(QtCore.QRect(170, 240, 841, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(startCollect_dialog)
        self.groupBox.setGeometry(QtCore.QRect(320, 100, 431, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.ew_fuzzy_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.ew_fuzzy_rbtn.setGeometry(QtCore.QRect(280, 10, 161, 21))
        self.ew_fuzzy_rbtn.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.ew_fuzzy_rbtn.setObjectName("ew_fuzzy_rbtn")
        self.ew_trust_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.ew_trust_rbtn.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.ew_trust_rbtn.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.ew_trust_rbtn.setChecked(True)
        self.ew_trust_rbtn.setObjectName("ew_trust_rbtn")
        self.groupBox_2 = QtWidgets.QGroupBox(startCollect_dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 160, 431, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.sn_fuzzy_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.sn_fuzzy_rbtn.setGeometry(QtCore.QRect(280, 0, 161, 21))
        self.sn_fuzzy_rbtn.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.sn_fuzzy_rbtn.setObjectName("sn_fuzzy_rbtn")
        self.sn_trust_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.sn_trust_rbtn.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.sn_trust_rbtn.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.sn_trust_rbtn.setChecked(True)
        self.sn_trust_rbtn.setObjectName("sn_trust_rbtn")
        self.stopcollect_btn = QtWidgets.QPushButton(startCollect_dialog)
        self.stopcollect_btn.setGeometry(QtCore.QRect(830, 160, 161, 41))
        self.stopcollect_btn.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.stopcollect_btn.setObjectName("stopcollect_btn")
        self.label_11 = QtWidgets.QLabel(startCollect_dialog)
        self.label_11.setGeometry(QtCore.QRect(1010, 270, 191, 51))
        self.label_11.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_11.setObjectName("label_11")
        self.ew_light_time = QtWidgets.QLineEdit(startCollect_dialog)
        self.ew_light_time.setGeometry(QtCore.QRect(1050, 320, 101, 31))
        self.ew_light_time.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.ew_light_time.setObjectName("ew_light_time")
        self.sn_light_time = QtWidgets.QLineEdit(startCollect_dialog)
        self.sn_light_time.setGeometry(QtCore.QRect(1050, 370, 101, 31))
        self.sn_light_time.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.sn_light_time.setObjectName("sn_light_time")

        self.retranslateUi(startCollect_dialog)
        QtCore.QMetaObject.connectSlotsByName(startCollect_dialog)

    def retranslateUi(self, startCollect_dialog):
        _translate = QtCore.QCoreApplication.translate
        startCollect_dialog.setWindowTitle(_translate("startCollect_dialog", "Dialog"))
        self.label.setText(_translate("startCollect_dialog", "推理演示"))
        self.label_2.setText(_translate("startCollect_dialog", "东西方向"))
        self.label_3.setText(_translate("startCollect_dialog", "南北方向"))
        self.startcollect_btn.setText(_translate("startCollect_dialog", "开始演示"))
        self.label_4.setText(_translate("startCollect_dialog", "当前数据"))
        self.label_5.setText(_translate("startCollect_dialog", "东西方向"))
        self.label_6.setText(_translate("startCollect_dialog", "南北方向"))
        self.label_7.setText(_translate("startCollect_dialog", "车流量"))
        self.label_8.setText(_translate("startCollect_dialog", "现阶段信号灯"))
        self.label_9.setText(_translate("startCollect_dialog", "开始时间"))
        self.label_10.setText(_translate("startCollect_dialog", "结束时间"))
        self.label_13.setText(_translate("startCollect_dialog", "东西方向推理流程"))
        self.label_14.setText(_translate("startCollect_dialog", "南北方向推理流程"))
        self.ew_fuzzy_rbtn.setText(_translate("startCollect_dialog", "模糊推理机"))
        self.ew_trust_rbtn.setText(_translate("startCollect_dialog", "可信度推理机"))
        self.sn_fuzzy_rbtn.setText(_translate("startCollect_dialog", "模糊推理机"))
        self.sn_trust_rbtn.setText(_translate("startCollect_dialog", "可信度推理机"))
        self.stopcollect_btn.setText(_translate("startCollect_dialog", "停止演示"))
        self.label_11.setText(_translate("startCollect_dialog", "下轮绿灯持续时间"))
