# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startcollect_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1160, 782)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(510, 20, 161, 51))
        self.label.setStyleSheet("\n"
"font: 20pt \"宋体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 111, 31))
        self.label_2.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 160, 111, 21))
        self.label_3.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(340, 110, 161, 21))
        self.radioButton.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(600, 110, 161, 21))
        self.radioButton_2.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(340, 160, 161, 21))
        self.radioButton_3.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(600, 160, 161, 21))
        self.radioButton_4.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(850, 120, 131, 51))
        self.pushButton.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 270, 111, 31))
        self.label_4.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(200, 320, 101, 31))
        self.label_5.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(200, 370, 101, 31))
        self.label_6.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(310, 280, 81, 31))
        self.label_7.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(680, 280, 141, 31))
        self.label_8.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(410, 280, 101, 31))
        self.label_9.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(560, 280, 91, 31))
        self.label_10.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(840, 280, 101, 31))
        self.label_11.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(1010, 280, 141, 31))
        self.label_12.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(310, 320, 71, 31))
        self.lineEdit.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 370, 71, 31))
        self.lineEdit_2.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(120, 510, 451, 201))
        self.textBrowser.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(660, 511, 461, 201))
        self.textBrowser_2.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(240, 470, 231, 21))
        self.label_13.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(790, 470, 231, 21))
        self.label_14.setStyleSheet("\n"
"font: 14pt \"宋体\";")
        self.label_14.setObjectName("label_14")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(400, 320, 121, 31))
        self.lineEdit_3.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(400, 370, 121, 31))
        self.lineEdit_4.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(550, 320, 121, 31))
        self.lineEdit_5.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(550, 370, 121, 31))
        self.lineEdit_6.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(710, 320, 71, 31))
        self.lineEdit_7.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(710, 370, 71, 31))
        self.lineEdit_8.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(830, 320, 121, 31))
        self.lineEdit_9.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(830, 370, 121, 31))
        self.lineEdit_10.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(990, 320, 121, 31))
        self.lineEdit_11.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(990, 370, 121, 31))
        self.lineEdit_12.setStyleSheet("\n"
"font: 12pt \"宋体\";")
        self.lineEdit_12.setObjectName("lineEdit_12")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "推理演示"))
        self.label_2.setText(_translate("Dialog", "东西方向"))
        self.label_3.setText(_translate("Dialog", "南北方向"))
        self.radioButton.setText(_translate("Dialog", "可信度推理机"))
        self.radioButton_2.setText(_translate("Dialog", "模糊推理机"))
        self.radioButton_3.setText(_translate("Dialog", "可信度推理机"))
        self.radioButton_4.setText(_translate("Dialog", "模糊推理机"))
        self.pushButton.setText(_translate("Dialog", "开始演示"))
        self.label_4.setText(_translate("Dialog", "当前数据"))
        self.label_5.setText(_translate("Dialog", "东西方向"))
        self.label_6.setText(_translate("Dialog", "南北方向"))
        self.label_7.setText(_translate("Dialog", "车流量"))
        self.label_8.setText(_translate("Dialog", "下阶段信号灯"))
        self.label_9.setText(_translate("Dialog", "开始时间"))
        self.label_10.setText(_translate("Dialog", "结束时间"))
        self.label_11.setText(_translate("Dialog", "开始时间"))
        self.label_12.setText(_translate("Dialog", "结束时间"))
        self.label_13.setText(_translate("Dialog", "东西方向推理流程"))
        self.label_14.setText(_translate("Dialog", "南北方向推理流程"))
